spring.application.name=order-service

spring.datasource.url:jdbc:postgresql://localhost:5432/order_service
spring.datasource.username:postgres
spring.datasource.password:8121960023@Aa

spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

erver.port=8080